scaleTargetRef:
  kind: Deployment
  name: "my-deployment"
#idleReplicaCount: 1
minReplicaCount: 2
maxReplicaCount: 5
cooldownPeriod: 30
pollingInterval: 10
triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated:9090
      metricName: "metric_name"
      query: |
        sum({series})
      threshold: "1"